---
- name: install utilities
  pacman:
    name:
      - aria2
      - curl
      - gvfs
      - htop
      - httpie
      - iotop
      - jq
      - less
      - nmap
      - ripgrep
      - rsync
      - shellcheck
      - udisks2
      - usbutils
      - which
      - evtest
  become: true

- name: install applications
  pacman:
    name:
      - chromium
      - evince
      - mpv
      - pcmanfm
      - viewnior
  become: true

- name: download spotify gpg key
  get_url:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    dest: /tmp/pubkey_0D811D58.gpg
    mode: '0440'

- name: import spotify gpg key
  command: gpg --import /tmp/pubkey_0D811D58.gpg

- name: install applications from AUR
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - google-chrome
    - lastpass
    - netextender
    - spotify
    - polybar-spotify-module
    # - franz

