---
- name: install audio tools
  pacman:
    name:
      - alsa-firmware
      - alsa-utils
      - paprefs
      - pavucontrol
      - pulseaudio
      - pulseaudio-alsa
      - mpd
  become: true

