---
- name: install audio tools
  pacman:
    name:
      - alsa-firmware
      - alsa-utils
      - paprefs
      - pavucontrol
      - pulseaudio
      - pulseaudio-alsa
      - mpd
  become: true

- name: download spotify gpg key
  get_url:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    dest: /tmp/pubkey_0D811D58.gpg
    mode: '0440'

- name: import spotify gpg key
  command: gpg --import /tmp/pubkey_0D811D58.gpg

- name: install AUR audio tools
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - spotify
    - polybar-spotify-module

- name: configure x11 key bindings
  copy:
    src: xbindkeysrc
    dest: /home/{{ archlinux_username }}/.xbindkeysrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"
