---

- name: install cli utilities
  pacman:
    name:
    - wget
    - unzip
  become: true

- name: Install cli packages from AUR
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - liquidprompt
  become: true



