---
- name: install git
  pacman:
    name: git
  become: true

- name: install tig
  pacman:
    name: tig
  become: true

- name: configure git name
  git_config:
    name: user.name
    value: "{{ archlinux_user_real_name }}"
    scope: global
  become: true
  become_user: "{{ archlinux_username }}"

- name: configure git email
  git_config:
    name: user.email
    value: "{{ archlinux_user_email }}"
    scope: global
  become: true
  become_user: "{{ archlinux_username }}"

- name: create global gitignore file
  file:
    path: /home/{{ archlinux_username }}/.gitignore
    state: touch
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

- name: configure global gitignore location
  git_config:
    name: core.excludesfile
    value: "~/.gitignore"
    scope: global
  become: true
  become_user: "{{ archlinux_username }}"

- name: configure global gitignore
  lineinfile:
    path: /home/{{ archlinux_username }}/.gitignore
    line: "{{ item }}"
  with_items:
    - "*.swo"
    - "*.swp"
    - ".DS_store"
    - ".direnv/"
    - ".envrc"
    - ".vagrant.d/"
    - ".ycm_extra_conf.py"
  become: true
  become_user: "{{ archlinux_username }}"
