---

- name: install utilities
  pacman:
    name:
    - virtualbox-guest-utils
    - virtualbox-ext-vnc
  become: true

- name: install k8s from AUR
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - virtualbox-bin
    - virtualbox-ext-oracle
    - virtualbox-guest-dkms
    - kubectl
    - minikube

- name: enable VirtualBox daemon
  systemd:
    name: vboxweb.service
    state: started
    enabled: true
  become: true
