---
- name: POLYBAR | install polybar from AUR
  aur:
    name: polybar
    user: "{{ archlinux_username }}"
  register: installresult

- name: POLYBAR | install special fonts 1/2
  package: 
    name: "{{ archlinux_username }}"
    state: present
  with_items:
    - bdf-unifont
  become: yes

- name: POLYBAR | install special fonts 2/2
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - siji-git

- name: POLYBAR | copy configuration files for "{{ archlinux_username }}"
  copy:
    src: user/.config/{{ item }}
    dest: /home/{{ archlinux_username }}/.config/
    owner: "{{ archlinux_username }}"
    group: "{{ archlinux_username }}"
    mode: 0644
    backup: yes
  with_items:
  - polybar

- name: POLYBAR | Set +x polybar config file
  file: 
    path: /home/{{ archlinux_username }}/.config/polybar/launch.sh
    mode: "u+x"
