---
- name: POLYBAR | install polybar from AUR
  aur:
    name: polybar
    user: "{{ archlinux_username }}"
  register: installresult

- name: POLYBAR | copy configuration files
  template:
    src: polybar/config
    dest: /home/{{ archlinux_username }}/.config/polybar
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: POLYBAR | Set +x polybar config file
  file: 
    path: /home/{{ archlinux_username }}/.config/polybar/launch.sh
    mode: "u+x"
