---
- name: install tmux
  pacman:
    name:
      - tmux
  become: true

  # run prefix + I to install all plugins
- name: clone tpm repo
  git:
      repo: 'https://github.com/tmux-plugins/tpm.git'
      dest: /home/{{ archlinux_username }}/.tmux/plugins/tpm
  become: true
  become_user: "{{ archlinux_username }}"

- name: install all tmux plugins
  command:
      cmd: ~/.tmux/plugins/tpm/bin/install_plugins
  become: true
  become_user: "{{ archlinux_username }}"

- name: install alacritty
  pacman:
    name:
      - alacritty
  become: true

