---

- name: install zsh
  pacman:
    name:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  become: true
  notify: change shell

- name: Ensure the cache folder with oh-my-zsh subfolder is present
  file:
    path: /home/{{ archlinux_username }}/.cache/oh-my-zsh
    owner: "{{ archlinux_username }}"
    group: "users"
    state: directory
    mode: 0755

- name: Ensure the last working dir file for oh-my-zsh is present
  file:
    path: /home/{{ archlinux_username }}/.cache/oh-my-zsh/last-working-dir
    owner: "{{ archlinux_username }}"
    group: "users"
    state: touch

- name: change user shell to zsh 
  hosts: localhost
  become: no
  vars:
    the_user: "{{ archlinux_username }}"
  tasks:
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

