---

- name: install zsh
  pacman:
    name:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  become: true

- name: Install zsh addons from AUR
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - zsh-history-substring-search
    - zsh-autosuggestions

- name: Backup .zshrc so oh-my-zsh won't fail trying to install
  command: mv ~/.zshrc ~/zshrc
  become: true
  become_user: "{{ archlinux_username }}"

- name: Install oh-my-zsh-git and optional dependencies from AUR
  aur: name={{ item }} user={{ archlinux_username }}
  with_items:
    - oh-my-zsh-git
    - oh-my-zsh-powerline-theme-git
  register: omzinstal

- name: Restore .zshrc 
  command: mv ~/zshrc ~/.zshrc
  become: true
  become_user: "{{ archlinux_username }}"

- name: Ensure the cache folder with oh-my-zsh subfolder is present
  file:
    path: /home/{{ archlinux_username }}/.cache/oh-my-zsh
    owner: "{{ archlinux_username }}"
    group: "users"
    state: directory
    mode: 0755

- name: Ensure the last working dir file for oh-my-zsh is present
  file:
    path: /home/{{ archlinux_username }}/.cache/oh-my-zsh/last-working-dir
    owner: "{{ archlinux_username }}"
    group: "users"
    state: touch

- name: change user shell to zsh 
  user:
    name: "{{ archlinux_username }}"
    shell: /bin/zsh
  become: true
