# include what you want
export TERM=xterm-256color

# Path to the oh-my-zsh installation
export ZSH=/usr/share/oh-my-zsh
export ZPLUG=/usr/share/zsh/scripts/zplug

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

## zsh History
HISTFILE=$HOME/.zhistory       # enable history saving on shell exit
setopt APPEND_HISTORY          # append rather than overwrite history file.
HISTSIZE=1000000000            # lines of history to maintain memory
SAVEHIST=$HISTSIZE             # lines of history to maintain in history file.
setopt HIST_EXPIRE_DUPS_FIRST  # allow dups, but expire old ones when I hit HISTSIZE
setopt EXTENDED_HISTORY        # save timestamp and runtime information
setopt no_share_history        # do not share history between terminal windows

# optional load time profiling
source ~/.profiling

# load all alias
source ~/.alias

# load liquidprompt
source /usr/bin/liquidprompt

# initialize zplug
ZPLUG_HOME=~/.zplug source $ZPLUG/init.zsh

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "laurenkt/zsh-vimto"

# # bind UP and DOWN arrow keys
zmodload zsh/terminfo
# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

export PATH=~/bin:/usr/local/bin:$PATH

# 10ms for key sequences
KEYTIMEOUT=1

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git-flow)

# load up oh-my-zsh
source $ZSH/oh-my-zsh.sh

# load up zplug plugins
if ! zplug check; then
    zplug install
fi
zplug load

# activate ESC trigger for zsh-vimto
export VIMTO_COLOR_NORMAL_TEXT=white
export VIMTO_COLOR_NORMAL_BACKGROUND=yellow
bindkey -v

# restore Ctrl-R backward incremental search
bindkey '^r' history-incremental-search-backward

# restore Ctrl-A as beginning of line
bindkey "^A" vi-beginning-of-line
bindkey "^E" vi-end-of-line

# kill a whole word with Alt+Backspace
backward-kill-dir () {
    local WORDCHARS=${WORDCHARS/\/}
    zle backward-kill-word
}
zle -N backward-kill-dir
bindkey '^[^?' backward-kill-dir

